### ISSUE TITLE
カレーをつくる

### ISSUE THREAD

**Issue by masahixixi** [taise/lvs_hack#1]
* シーフードとビーフの2種類
* 買い出しはなかにし + 2名くらい
  * 集合の1時間前くらいに集まって買いたい
* 料理対決をするかしないかはその場のノリ

**Comment by masahixixi** [comment]
yamap が手伝ってくれる

**Comment by masahixixi** [comment]
うちかわさんもてつだってくれる

**Comment by ruchikawa** [comment]
http://housefoods.jp/recipe/rcp_00014543.html
これの5倍買えばいいですかね。
カレールーは多めに4個とかでも良いかもですねー。
