### ISSUE TITLE
リポジトリ名をlv_hackに変えて汎用化する

### ISSUE THREAD

**Issue by onunu** [taise/lvs_hack#5]
今のままだと今回しか使えないのでlvs_hackに変えて次回以降も使っていく、というのはどうでしょう？
しおりをwikiにするか、ディレクトリ切って適宜`README.md`を追加する、という方針にできるとしおり担当としてありがたいです

**Comment by taise** [comment]
リポジトリ名変更します〜

**Comment by taise** [comment]
`ディレクトリ切って適宜README.mdを追加する`が、任意のエディタで編集できて楽かなーと思います
